// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJDUp8ruVeiktyFL1YvARJbP8p0nZDIzw',
    appId: '1:69144239613:web:e37cdbafc4bc44a1744d94',
    messagingSenderId: '69144239613',
    projectId: 'firebaseauth666',
    authDomain: 'fir-auth666.firebaseapp.com',
    storageBucket: 'firebaseauth666.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMdqtrbn6pt794sKmfZAO_a7Oek_vPE48',
    appId: '1:69144239613:android:e3c7e1549293375a744d94',
    messagingSenderId: '69144239613',
    projectId: 'firebaseauth666',
    storageBucket: 'firebaseauth666.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbgM33VS2iAd_XPYPLFf_a9_C0_ge0lSE',
    appId: '1:69144239613:ios:a3ffa0959aabfa86744d94',
    messagingSenderId: '69144239613',
    projectId: 'firebaseauth666',
    storageBucket: 'firebaseauth666.appspot.com',
    iosBundleId: 'com.example.madf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbgM33VS2iAd_XPYPLFf_a9_C0_ge0lSE',
    appId: '1:69144239613:ios:a3ffa0959aabfa86744d94',
    messagingSenderId: '69144239613',
    projectId: 'firebaseauth666',
    storageBucket: 'firebaseauth666.appspot.com',
    iosBundleId: 'com.example.madf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJDUp8ruVeiktyFL1YvARJbP8p0nZDIzw',
    appId: '1:69144239613:web:d36f4793c2dc5ecd744d94',
    messagingSenderId: '69144239613',
    projectId: 'firebaseauth666',
    authDomain: 'fir-auth666.firebaseapp.com',
    storageBucket: 'firebaseauth666.appspot.com',
  );
}
